version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  api_gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./users_serv:/app/users_serv
    depends_on:
      - user_service
      - post_service
    environment:
      - TZ=Europe/Moscow
      - PYTHONPATH=/app:/app/proto
    networks:
      - my_network

  user_service:
    build:
      context: .
      dockerfile: users_serv/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - TZ=Europe/Moscow
      - PYTHONPATH=/app:/app/broker
    networks:
      - my_network

  post_service:
    build:
      context: .
      dockerfile: posts_serv/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - TZ=Europe/Moscow
      - PYTHONPATH=/app:/app/proto:/app/broker
    networks:
      - my_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: user_db,post_db
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - my_network

  tests_api_gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    volumes:
      - ./api-gateway:/app/api-gateway
      - ./proto:/app/proto
      - ./users_serv:/app/users_serv
      - ./posts_serv:/app/posts_serv
    command: ["./api-gateway/wait-for-it.sh", "users_serv:5000", "--", "pytest", "tests/"]
    depends_on:
      - api_gateway
      - user_service
      - post_service
      - db
      - kafka
    environment:
      - FLASK_ENV=testing
      - TZ=Europe/Moscow
      - PYTHONPATH=/app:/app/proto:/app/posts_serv:/app/api-gateway:/app/broker
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - my_network

  unit_tests_userv:
    build:
      context: .
      dockerfile: users_serv/Dockerfile
    volumes:
      - ./users_serv:/app
      - ./users_serv/tests:/app/tests
      - ./broker:/app/broker
    command: [ "pytest", "tests/" ]
    depends_on:
      - db
      - kafka
    environment:
      - FLASK_ENV=testing
      - TZ=Europe/Moscow
      - PYTHONPATH=/app:/app/broker
    networks:
      - my_network

  unit_tests_pserv:
    build:
      context: .
      dockerfile: posts_serv/Dockerfile
    volumes:
      - ./posts_serv:/app
      - ./posts_serv/tests:/app/tests
      - ./proto:/app/proto
      - ./broker:/app/broker
    command: [ "pytest", "tests/" ]
    depends_on:
      - db
      - kafka
    environment:
      - FLASK_ENV=testing
      - TZ=Europe/Moscow
      - PYTHONPATH=/app:/app/proto:/app/broker
    networks:
      - my_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - my_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - my_network

volumes:
  postgres_data: